// Builds the format tables that live outside the app - the website's and the
// README's - from the list the app's own "supported formats" dialog is built
// from. Run automatically before dev/build/test alongside the other metadata
// generators, for the same reason: every table outside the app is a copy of
// what it supports, and a copy is a thing that drifts.
//
// Both tables are rendered here rather than by a script each, so the two can
// never disagree about a format. What the app knows - names, suffixes,
// abilities, codecs - comes from archivePaths.ts; the prose and the detail no
// screen shows come from formatDocs.json beside this file.
//
// The output is committed, because the Pages workflow builds the site with
// Hugo alone and never runs npm - so what is in the repository is what ships.
const fs = require('fs')
const path = require('path')
const { pathToFileURL } = require('url')

const repoRoot = path.resolve(__dirname, '..')
const sourcePath = path.join(repoRoot, 'src', 'renderer', 'src', 'utils', 'archivePaths.ts')
const docsPath = path.join(__dirname, 'formatDocs.json')
const outputPath = path.join(repoRoot, 'site', 'data', 'formats.json')
const readmePath = path.join(repoRoot, 'README.md')

const BEGIN_MARKER = '<!-- begin generated format table -->'
const END_MARKER = '<!-- end generated format table -->'

/** How the README names each ability, which is wordier than the site's column. */
const README_ABILITIES = [
  ['compress', 'Compress'],
  ['extract', 'Extract'],
  ['read', 'Preview'],
  ['password', 'Password create/extract'],
  ['split', 'Split volumes']
]

async function readFormats() {
  // Node reads the TypeScript source directly, so this is the app's own list
  // rather than a transcription of it. The path goes through pathToFileURL
  // because a Windows path is not a URL by concatenation.
  const { SUPPORTED_FORMATS } = await import(pathToFileURL(sourcePath).href)
  const docs = JSON.parse(fs.readFileSync(docsPath, 'utf8')).formats

  return SUPPORTED_FORMATS.map(format => {
    const extra = docs[format.name]
    if (!extra) throw new Error(`No formatDocs.json entry for ${format.name}`)
    return {
      name: format.name,
      extensions: [...format.extensions],
      compress: format.compress,
      extract: format.extract,
      read: format.read,
      password: format.password,
      split: format.split,
      codecs: { write: [...format.codecs.write], read: [...format.codecs.read] },
      encryption: extra.encryption ? [...extra.encryption] : [],
      readFilters: extra.readFilters ? [...extra.readFilters] : [],
      notes: extra.notes
    }
  })
}

/**
 * The site reads the facts alone; its own labels come from the content files,
 * and the README-only prose is named nowhere here rather than stripped, so a
 * field added for the README cannot reach the site by accident.
 */
function siteData(formats) {
  return {
    comment: 'Generated by scripts/generateFormatTables.cjs - edit archivePaths.ts instead.',
    formats: formats.map(format => ({
      name: format.name,
      extensions: format.extensions,
      compress: format.compress,
      extract: format.extract,
      read: format.read,
      password: format.password,
      split: format.split,
      codecs: format.codecs
    }))
  }
}

/** The codec cell, which names a direction only when the two lists differ. */
function codecCell(format) {
  const lines = []
  const write = format.codecs.write.join(', ')
  const read = format.codecs.read.join(', ')
  if (!write && !read) lines.push('None')
  else if (write === read) lines.push(read)
  else {
    if (write) lines.push(`Write: ${write}`)
    lines.push(`Read: ${read}`)
  }
  if (format.encryption.length) lines.push(`Encryption: ${format.encryption.join(', ')}`)
  if (format.readFilters.length) lines.push(`(Read) Filters: ${format.readFilters.join(', ')}`)
  return lines.join('<br>')
}

function readmeTable(formats) {
  const rows = formats.map(format => {
    const abilities = README_ABILITIES.filter(([key]) => format[key]).map(([, label]) => label)
    return `| ${format.name} | ${format.extensions.join(' ')} | ${abilities.join(' · ')} | ${codecCell(format)} | ${format.notes} |`
  })
  return [
    '| Format | Extensions | Supported features | Codec support | Notes |',
    '| --- | --- | --- | --- | --- |',
    ...rows
  ].join('\n')
}

function writeReadme(formats) {
  const readme = fs.readFileSync(readmePath, 'utf8')
  const begin = readme.indexOf(BEGIN_MARKER)
  const end = readme.indexOf(END_MARKER)
  if (begin === -1 || end === -1) {
    throw new Error(`README.md is missing the ${BEGIN_MARKER} / ${END_MARKER} pair`)
  }
  const updated = `${readme.slice(0, begin + BEGIN_MARKER.length)}\n${readmeTable(formats)}\n${readme.slice(end)}`
  fs.writeFileSync(readmePath, updated)
  return updated
}

async function generate() {
  const formats = await readFormats()
  const data = siteData(formats)

  fs.mkdirSync(path.dirname(outputPath), { recursive: true })
  fs.writeFileSync(outputPath, `${JSON.stringify(data, null, 2)}\n`)
  writeReadme(formats)
  return { formats, data }
}

if (require.main === module) {
  generate().then(({ formats }) => {
    console.log(`Wrote ${formats.length} formats to ${path.relative(repoRoot, outputPath)} and README.md`)
  }, error => {
    console.error(error)
    process.exitCode = 1
  })
}

module.exports = { generate, readFormats, readmeTable, siteData, outputPath, readmePath }
