// Builds the format table the website renders, from the same list the app's
// own "supported formats" dialog is built from. Run automatically before
// dev/build/test alongside the other metadata generators, for the same reason:
// the site is a separate copy of what the app supports, and a separate copy is
// a copy that drifts.
//
// The output is committed, because the Pages workflow builds the site with
// Hugo alone and never runs npm - so what is in the repository is what ships.
const fs = require('fs')
const path = require('path')
const { pathToFileURL } = require('url')

const repoRoot = path.resolve(__dirname, '..')
const sourcePath = path.join(repoRoot, 'src', 'renderer', 'src', 'utils', 'archivePaths.ts')
const outputPath = path.join(repoRoot, 'site', 'data', 'formats.json')

async function generate() {
  // Node reads the TypeScript source directly, so this is the app's own list
  // rather than a transcription of it. The path goes through pathToFileURL
  // because a Windows path is not a URL by concatenation.
  const { SUPPORTED_FORMATS } = await import(pathToFileURL(sourcePath).href)

  const formats = SUPPORTED_FORMATS.map(format => ({
    name: format.name,
    extensions: [...format.extensions],
    compress: format.compress,
    extract: format.extract,
    read: format.read,
    password: format.password,
    split: format.split,
    codecs: {
      write: [...format.codecs.write],
      read: [...format.codecs.read]
    }
  }))

  const data = {
    comment: 'Generated by scripts/generateSiteFormats.cjs - edit archivePaths.ts instead.',
    formats
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true })
  fs.writeFileSync(outputPath, `${JSON.stringify(data, null, 2)}\n`)
  return data
}

if (require.main === module) {
  generate().then(data => {
    console.log(`Wrote site formats to ${path.relative(repoRoot, outputPath)}: ${data.formats.length} formats`)
  }, error => {
    console.error(error)
    process.exitCode = 1
  })
}

module.exports = { generate, outputPath }
